version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: todo_mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: todo_analytics
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  app:
    build: .
    container_name: todo_app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://admin:password@mongodb:27017/todo_analytics?authSource=admin
      - SESSION_SECRET=your-super-secret-session-key-change-this-in-production
    depends_on:
      - mongodb
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - ./views:/app/views

volumes:
  mongodb_data:
